# Generated by Django 3.2.4 on 2021-06-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_stock_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=200)),
                ('stock_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='stockcode',
            index=models.Index(fields=['stock'], name='core_stockc_stock_326dce_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcode',
            constraint=models.UniqueConstraint(fields=('stock',), name='unique_stock'),
        ),
    ]
